export const INITIAL_CATEGORIES = [
  { id: 1, name: "Kỹ năng sống" },
  { id: 2, name: "Văn học nước ngoài" },
  { id: 3, name: "Văn học Việt Nam" },
  { id: 4, name: "Kinh tế - Kinh doanh" },
  { id: 5, name: "Tâm lý học" },
  { id: 6, name: "Thiếu nhi" },
];

export const INITIAL_BOOKS = [
  {
    id: 1,
    shopId: 1,
    shopName: "Nhà sách Phương Nam",
    categoryId: 1,
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    publisher: "NXB Tổng hợp TP.HCM",
    price: 89000,
    stock: 120,
    rating: 4.8,
    reviewCount: 2341,
    description:
      "Cuốn sách kinh điển về nghệ thuật giao tiếp và tạo thiện cảm với mọi người, đã được dịch ra hơn 30 thứ tiếng.",
    coverColor: "#1d4ed8",
    coverColor2: "#3b82f6",
    status: "ACTIVE",
  },
  {
    id: 2,
    shopId: 1,
    shopName: "Nhà sách Phương Nam",
    categoryId: 2,
    title: "Nhà Giả Kim",
    author: "Paulo Coelho",
    publisher: "NXB Hội Nhà Văn",
    price: 79000,
    stock: 85,
    rating: 4.7,
    reviewCount: 1892,
    description:
      "Hành trình đi tìm kho báu của cậu bé chăn cừu Santiago, một tác phẩm truyền cảm hứng bất hủ.",
    coverColor: "#b45309",
    coverColor2: "#f59e0b",
    status: "ACTIVE",
  },
  {
    id: 3,
    shopId: 2,
    shopName: "Fahasa Online",
    categoryId: 5,
    title: "Sapiens: Lược Sử Loài Người",
    author: "Yuval Noah Harari",
    publisher: "NXB Tri Thức",
    price: 145000,
    stock: 43,
    rating: 4.9,
    reviewCount: 3102,
    description:
      "Câu chuyện kỳ thú về 70.000 năm lịch sử loài người từ thời tiền sử đến thời đại AI.",
    coverColor: "#065f46",
    coverColor2: "#10b981",
    status: "ACTIVE",
  },
  {
    id: 4,
    shopId: 2,
    shopName: "Fahasa Online",
    categoryId: 5,
    title: "Tư Duy Nhanh Và Chậm",
    author: "Daniel Kahneman",
    publisher: "NXB Thế Giới",
    price: 125000,
    stock: 0,
    rating: 4.6,
    reviewCount: 987,
    description:
      "Khám phá hai hệ thống tư duy chi phối mọi quyết định trong cuộc sống của chúng ta.",
    coverColor: "#6d28d9",
    coverColor2: "#8b5cf6",
    status: "OUT_OF_STOCK",
  },
  {
    id: 5,
    shopId: 3,
    shopName: "Sách Tiki",
    categoryId: 4,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    publisher: "NXB Trẻ",
    price: 98000,
    stock: 200,
    rating: 4.5,
    reviewCount: 4521,
    description:
      "Bài học về tiền bạc từ người cha giàu và người cha nghèo, thay đổi cách nghĩ về tài chính.",
    coverColor: "#92400e",
    coverColor2: "#d97706",
    status: "ACTIVE",
  },
  {
    id: 6,
    shopId: 1,
    shopName: "Nhà sách Phương Nam",
    categoryId: 1,
    title: "Atomic Habits",
    author: "James Clear",
    publisher: "NXB Lao Động",
    price: 135000,
    stock: 67,
    rating: 4.8,
    reviewCount: 2876,
    description:
      "Phương pháp xây dựng thói quen tốt và phá bỏ thói quen xấu dựa trên khoa học hành vi.",
    coverColor: "#0e7490",
    coverColor2: "#06b6d4",
    status: "ACTIVE",
  },
  {
    id: 7,
    shopId: 3,
    shopName: "Sách Tiki",
    categoryId: 3,
    title: "Mắt Biếc",
    author: "Nguyễn Nhật Ánh",
    publisher: "NXB Trẻ",
    price: 62000,
    stock: 150,
    rating: 4.9,
    reviewCount: 5234,
    description:
      "Câu chuyện tình buồn giữa Ngạn và Hà Lan — mối tình tuổi học trò đẹp và đau đớn.",
    coverColor: "#b91c1c",
    coverColor2: "#ef4444",
    status: "ACTIVE",
  },
  {
    id: 8,
    shopId: 2,
    shopName: "Fahasa Online",
    categoryId: 3,
    title: "Cho Tôi Xin Một Vé Đi Tuổi Thơ",
    author: "Nguyễn Nhật Ánh",
    publisher: "NXB Trẻ",
    price: 59000,
    stock: 210,
    rating: 4.8,
    reviewCount: 3789,
    description:
      "Hành trình trở về tuổi thơ đầy màu sắc và kỷ niệm khó quên của một người đàn ông trưởng thành.",
    coverColor: "#7c3aed",
    coverColor2: "#a78bfa",
    status: "ACTIVE",
  },
  {
    id: 9,
    shopId: 3,
    shopName: "Sách Tiki",
    categoryId: 1,
    title: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    author: "Rosie Nguyễn",
    publisher: "NXB Hội Nhà Văn",
    price: 72000,
    stock: 88,
    rating: 4.4,
    reviewCount: 1243,
    description:
      "Cuốn sách dành cho những bạn trẻ đang loay hoay tìm kiếm con đường và định hướng cho bản thân.",
    coverColor: "#047857",
    coverColor2: "#34d399",
    status: "ACTIVE",
  },
  {
    id: 10,
    shopId: 1,
    shopName: "Nhà sách Phương Nam",
    categoryId: 6,
    title: "Harry Potter và Hòn Đá Phù Thủy",
    author: "J.K. Rowling",
    publisher: "NXB Trẻ",
    price: 120000,
    stock: 95,
    rating: 4.9,
    reviewCount: 6102,
    description:
      "Cuộc phiêu lưu kỳ diệu của cậu bé Harry Potter tại trường phù thủy Hogwarts huyền bí.",
    coverColor: "#1e3a5f",
    coverColor2: "#2563eb",
    status: "ACTIVE",
  },
  {
    id: 11,
    shopId: 2,
    shopName: "Fahasa Online",
    categoryId: 4,
    title: "Cà Phê Cùng Tony",
    author: "Tony Buổi Sáng",
    publisher: "NXB Trẻ",
    price: 68000,
    stock: 175,
    rating: 4.3,
    reviewCount: 892,
    description:
      "Những câu chuyện truyền cảm hứng về kinh doanh, cuộc sống và bài học từ thực tế.",
    coverColor: "#92400e",
    coverColor2: "#f59e0b",
    status: "ACTIVE",
  },
  {
    id: 12,
    shopId: 3,
    shopName: "Sách Tiki",
    categoryId: 2,
    title: "Bố Già",
    author: "Mario Puzo",
    publisher: "NXB Văn Học",
    price: 115000,
    stock: 55,
    rating: 4.7,
    reviewCount: 1567,
    description:
      "Tiểu thuyết kinh điển về gia tộc mafia Corleone — một trong những tác phẩm vĩ đại nhất thế kỷ 20.",
    coverColor: "#374151",
    coverColor2: "#6b7280",
    status: "ACTIVE",
  },
];

export const INITIAL_ORDERS = [
  {
    id: 1001,
    customerId: 1,
    customerName: "Nguyễn Văn An",
    customerPhone: "0901234567",
    shopId: 1,
    items: [
      { book: INITIAL_BOOKS[0], quantity: 1, unitPrice: 89000 },
      { book: INITIAL_BOOKS[5], quantity: 2, unitPrice: 135000 },
    ],
    totalAmount: 359000,
    shippingFee: 30000,
    orderStatus: "DELIVERED",
    paymentStatus: "PAID",
    paymentMethod: "ONLINE",
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
    createdAt: "2024-01-15 09:23",
    updatedAt: "2024-01-18 14:30",
    tracking: {
      number: "GHN123456789",
      carrier: "Giao Hàng Nhanh",
      status: "DELIVERED",
      estimated: "2024-01-18",
      actualDelivered: "2024-01-18 14:30",
    },
    feedback: {
      rating: 5,
      content: "Sách đóng gói cẩn thận, giao hàng nhanh, rất hài lòng!",
      type: "SHOP",
      createdAt: "2024-01-19",
      customer: "Nguyễn Văn An",
    },
  },
  {
    id: 1002,
    customerId: 1,
    customerName: "Nguyễn Văn An",
    customerPhone: "0901234567",
    shopId: 2,
    items: [{ book: INITIAL_BOOKS[2], quantity: 1, unitPrice: 145000 }],
    totalAmount: 145000,
    shippingFee: 25000,
    orderStatus: "SHIPPED",
    paymentStatus: "PAID",
    paymentMethod: "ONLINE",
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
    createdAt: "2024-01-20 11:05",
    updatedAt: "2024-01-21 08:00",
    tracking: {
      number: "GHN987654321",
      carrier: "Giao Hàng Nhanh",
      status: "TRANSIT",
      estimated: "2024-01-23",
    },
  },
  {
    id: 1003,
    customerId: 1,
    customerName: "Nguyễn Văn An",
    customerPhone: "0901234567",
    shopId: 3,
    items: [
      { book: INITIAL_BOOKS[6], quantity: 1, unitPrice: 62000 },
      { book: INITIAL_BOOKS[7], quantity: 1, unitPrice: 59000 },
    ],
    totalAmount: 121000,
    shippingFee: 20000,
    orderStatus: "PENDING",
    paymentStatus: "UNPAID",
    paymentMethod: "COD",
    shippingAddress: "123 Nguyễn Huệ, Quận 1, TP.HCM",
    createdAt: "2024-01-22 16:44",
    updatedAt: "2024-01-22 16:44",
  },
  {
    id: 1004,
    customerId: 2,
    customerName: "Trần Thị Bích",
    customerPhone: "0912345678",
    shopId: 1,
    items: [{ book: INITIAL_BOOKS[9], quantity: 1, unitPrice: 120000 }],
    totalAmount: 120000,
    shippingFee: 30000,
    orderStatus: "RETURNED",
    paymentStatus: "REFUNDED",
    paymentMethod: "ONLINE",
    shippingAddress: "456 Lê Lợi, Quận 3, TP.HCM",
    createdAt: "2024-01-10 10:00",
    updatedAt: "2024-01-17 09:00",
    returnRequest: {
      reason: "Sách bị rách bìa, không đúng như mô tả",
      reasonType: "DAMAGED",
      status: "APPROVED",
      refundAmount: 120000,
      createdAt: "2024-01-15",
    },
  },
  {
    id: 1005,
    customerId: 3,
    customerName: "Lê Minh Tuấn",
    customerPhone: "0923456789",
    shopId: 2,
    items: [
      { book: INITIAL_BOOKS[4], quantity: 2, unitPrice: 98000 },
      { book: INITIAL_BOOKS[10], quantity: 1, unitPrice: 68000 },
    ],
    totalAmount: 264000,
    shippingFee: 25000,
    orderStatus: "PROCESSING",
    paymentStatus: "PAID",
    paymentMethod: "ONLINE",
    shippingAddress: "789 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
    createdAt: "2024-01-21 14:30",
    updatedAt: "2024-01-22 09:00",
  },
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 1,
    orderId: 1001,
    amount: 389000,
    type: "ONLINE",
    paidBy: "CUSTOMER",
    createdAt: "2024-01-15 09:25",
    code: "VNP20240115092512",
  },
  {
    id: 2,
    orderId: 1001,
    amount: 30000,
    type: "SHIPPING_FEE",
    paidBy: "CUSTOMER",
    createdAt: "2024-01-15 09:25",
  },
  {
    id: 3,
    orderId: 1001,
    amount: 329000,
    type: "SHOP_REVENUE",
    paidBy: "PLATFORM",
    createdAt: "2024-01-18 16:00",
  },
  {
    id: 4,
    orderId: 1002,
    amount: 170000,
    type: "ONLINE",
    paidBy: "CUSTOMER",
    createdAt: "2024-01-20 11:07",
    code: "VNP20240120110734",
  },
  {
    id: 5,
    orderId: 1004,
    amount: 150000,
    type: "ONLINE",
    paidBy: "CUSTOMER",
    createdAt: "2024-01-10 10:02",
    code: "VNP20240110100234",
  },
  {
    id: 6,
    orderId: 1004,
    amount: 120000,
    type: "REFUND",
    paidBy: "PLATFORM",
    createdAt: "2024-01-17 09:30",
  },
  {
    id: 7,
    orderId: 1005,
    amount: 289000,
    type: "ONLINE",
    paidBy: "CUSTOMER",
    createdAt: "2024-01-21 14:32",
    code: "VNP20240121143256",
  },
];

export const INITIAL_DELIVER_TASKS = [
  {
    id: 1,
    orderId: 1002,
    trackingNumber: "GHN987654321",
    customer: "Nguyễn Văn An",
    address: "123 Nguyễn Huệ, Q.1, TP.HCM",
    phone: "0901234567",
    status: "TRANSIT",
    items: 1,
    weight: "0.3kg",
    estimatedDate: "23/01/2024",
  },
  {
    id: 2,
    orderId: 1005,
    trackingNumber: "GHN111222333",
    customer: "Lê Minh Tuấn",
    address: "789 Điện Biên Phủ, Q.BT, TP.HCM",
    phone: "0923456789",
    status: "PENDING",
    items: 3,
    weight: "0.8kg",
    estimatedDate: "24/01/2024",
  },
  {
    id: 3,
    orderId: 999,
    trackingNumber: "GHN444555666",
    customer: "Phạm Thị Hoa",
    address: "22 Trần Hưng Đạo, Q.5, TP.HCM",
    phone: "0934567890",
    status: "OUT_FOR_DELIVERY",
    items: 2,
    weight: "0.5kg",
    estimatedDate: "22/01/2024",
  },
];

export const DEMO_USERS = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    email: "an.nguyen@email.com",
    role: "customer",
    phone: "0901234567",
    createdAt: "01/10/2023",
  },
  {
    id: 2,
    name: "Trần Thị Bích",
    email: "bich.tran@email.com",
    role: "customer",
    phone: "0912345678",
    createdAt: "15/10/2023",
  },
  {
    id: 3,
    name: "Lê Minh Tuấn",
    email: "tuan.le@email.com",
    role: "customer",
    phone: "0923456789",
    createdAt: "20/11/2023",
  },
  {
    id: 4,
    name: "Nhà sách Phương Nam",
    email: "phuongnam@shop.com",
    role: "shop",
    shopId: 1,
    shopName: "Nhà sách Phương Nam",
    phone: "02838225340",
    createdAt: "01/01/2023",
  },
  {
    id: 5,
    name: "Fahasa Online",
    email: "fahasa@shop.com",
    role: "shop",
    shopId: 2,
    shopName: "Fahasa Online",
    phone: "1900636467",
    createdAt: "15/01/2023",
  },
  {
    id: 6,
    name: "Sách Tiki",
    email: "tiki@shop.com",
    role: "shop",
    shopId: 3,
    shopName: "Sách Tiki",
    phone: "19006035",
    createdAt: "20/01/2023",
  },
  {
    id: 7,
    name: "Nguyễn Văn Giao",
    email: "giao@deliver.com",
    role: "deliver",
    phone: "0934567890",
    createdAt: "01/06/2023",
  },
  {
    id: 8,
    name: "Admin System",
    email: "admin@bookshop.com",
    role: "admin",
    createdAt: "01/01/2023",
  },
];
